id: cce729995d15424690c54860fd1f263c
title: Toh_543-The_Root_Manual_of_the_Rites_of_Manjusri-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-038
  eft-text-version: 1.21.2 2020
